### ISSUE TITLE
Remove dead links

### ISSUE THREAD

**Issue by demonno** [safareli/fp-stuff#3]
Some dead links detected
- `Monads in Dynamically-Typed Languages` - http://eighty-twenty.org/2015/01/25/monads-in-dynamically-typed-languages/` - `404 Not Found`
- `Monads, Monoids, and Make Believe` - https://www.youtube.com/watch?v=ww2Z1URx-G0 -`Private now`

**Comment by safareli** [comment]
Thanks!
